version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins1
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app1
    ports:
      - "3000:80"
    depends_on:
      - jenkins

volumes:
  jenkins_home:
